#!/usr/bin/env bash
# Displays numbers 1 to 100, with FizzBuzz for multiples of 3 and/or 5
for i in {1..100}
do
	if [ $((i % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
